[package]
name = "radix-engine-toolkit-uniffi"
version = "0.10.0-elm.1"
edition = "2021"
build = "build.rs"

[dependencies]
# radixdlt-scrypto dependencies.
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "elm-970ed2bf3", features = ["serde"] }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "elm-970ed2bf3", features = ["serde"] }
transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "elm-970ed2bf3" }
radix-engine = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "elm-970ed2bf3", default-features= false, features = ["std", "lru"] }
radix-engine-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "elm-970ed2bf3", features = ["serde"] }

# Core Radix Engine Toolkit
radix-engine-toolkit-core = { path = "../radix-engine-toolkit-core" }

# The UniFFI crate for generating bindings to other languages
uniffi = { git = "https://github.com/0xOmarA/uniffi-rs/", rev = "2795d19745989f68396ea6fe1d50c1df1ad87528", features = ["cli"] }
hex = "0.4.3"
thiserror = "1.0.40"
paste = "1.0.12"

[build-dependencies]
# The UniFFI crate for generating bindings to other languages
uniffi = { git = "https://github.com/0xOmarA/uniffi-rs/", rev = "2795d19745989f68396ea6fe1d50c1df1ad87528", features = ["build"] }

[dev-dependencies]
# The UniFFI crate for generating bindings to other languages
uniffi = { git = "https://github.com/0xOmarA/uniffi-rs/", rev = "2795d19745989f68396ea6fe1d50c1df1ad87528", features = ["bindgen-tests"] }

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[profile.release]
incremental = false
panic = 'abort'
codegen-units = 1
