[package]
name = "radix-engine-toolkit-uniffi"
version = "0.10.0"
edition = "2021"
build = "build.rs"

[dependencies]
# radixdlt-scrypto dependencies.
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "feature/typed-native-events", features = ["serde"] }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "feature/typed-native-events", features = ["serde"] }
transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "feature/typed-native-events" }
radix-engine = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "feature/typed-native-events", default-features= false, features = ["std", "lru"] }
radix-engine-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "feature/typed-native-events", features = ["serde"] }

# Core Radix Engine Toolkit
radix-engine-toolkit-core = { path = "../radix-engine-toolkit-core" }

# The UniFFI crate for generating bindings to other languages
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "fe0d47ab23267415d118e5318feb282cc99ed5d0", features = ["cli"] }
hex = "0.4.3"
thiserror = "1.0.40"
paste = "1.0.12"

[build-dependencies]
# The UniFFI crate for generating bindings to other languages
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "fe0d47ab23267415d118e5318feb282cc99ed5d0", features = ["build"] }

[dev-dependencies]
# The UniFFI crate for generating bindings to other languages
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "fe0d47ab23267415d118e5318feb282cc99ed5d0", features = ["bindgen-tests"] }

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[profile.release]
incremental = false
panic = 'abort'
codegen-units = 1
